### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by newmacwkl** [bytedance/AabResGuard#38]
```
Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/impldep/org/eclipse/jgit/errors/NotSupportedException
	at com.bytedance.android.plugin.internal.SigningConfigResolutionKt.getSigningConfigForAGP4(SigningConfigResolution.kt:46)
	at com.bytedance.android.plugin.internal.SigningConfigResolutionKt.getSigningConfig(SigningConfigResolution.kt:27)
	at com.bytedance.android.plugin.tasks.AabResGuardTask.execute(AabResGuardTask.kt:47)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

**Expected behavior**
gradlew clean bundleRelease

**Info (please complete the following information):**
 - Device: [Windows]
 - OS: [10]
 - AabResGuard  version [0.1.7]
 - Android studio version: [Android Studio 4.1] 
 - AGP version: [com.android.tools.build:gradle:4.0.1]
 - Gradle version: [gradle-6.1.1]

**Comment by qinRight** [comment]
![image](https://user-images.githubusercontent.com/38930890/107169764-a15e0a00-69f9-11eb-9bfe-25f37aea4c16.png)
![image](https://user-images.githubusercontent.com/38930890/107170386-25fd5800-69fb-11eb-90bb-a86d41c2afbd.png)

[0.1.5, 0.1.6, 0.1.7]  AabResGuardExtension.java error
