### ISSUE TITLE
[Command Line not working] 

### ISSUE THREAD

**Issue by alma359** [bytedance/AabResGuard#43]
**Describe the bug**
Trying to run the command line version with default config results in an Error.

**Log:**
java -jar AabResGuard-0.1.7.jar obfuscate-bundle --bundle=app-release.aab --output=obfuscated.aab --config=config.xml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by shadow.bytedance.com.google.protobuf.UnsafeUtil (file:/app/AabResGuard-0.1.7.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of shadow.bytedance.com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
analyze bundle file done, const 212
[BT:0.9.0] Error: null
java.lang.NullPointerException
	at com.bytedance.android.aabresguard.executors.ResourcesObfuscator.<init>(ResourcesObfuscator.java:73)
	at com.bytedance.android.aabresguard.commands.ObfuscateBundleCommand.execute(ObfuscateBundleCommand.java:217)
	at com.bytedance.android.aabresguard.AabResGuardMain.main(AabResGuardMain.java:51)
	at com.bytedance.android.aabresguard.AabResGuardMain.main(AabResGuardMain.java:26)

**Comment by luckyjmcc** [comment]
java -jar AabResGuard-0.1.7.jar obfuscate-bundle --bundle=app-release.aab --output=obfuscated.aab --config=config.xml ---->output=obfuscated.aab
getOutputPath().getParent() ----> null 

Solution : create a folder and change command line : 
java -jar AabResGuard-0.1.7.jar obfuscate-bundle --bundle=app-release.aab --output=yourfoldername\obfuscated.aab --config=config.xml
