### ISSUE TITLE
Command line 报错

### ISSUE THREAD

**Issue by luckyjmcc** [bytedance/AabResGuard#60]
[BT:0.9.0] Error: Cannot run program "jarsigner.exe": CreateProcess error=2, 系统找不到指定的文件。
java.io.IOException: Cannot run program "jarsigner.exe": CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at com.bytedance.android.aabresguard.android.OpenJDKJarSigner.start(OpenJDKJarSigner.java:87)
        at com.bytedance.android.aabresguard.android.OpenJDKJarSigner.sign(OpenJDKJarSigner.java:66)
        at com.bytedance.android.aabresguard.android.JarSigner.sign(JarSigner.java:17)
        at com.bytedance.android.aabresguard.bundle.AppBundleSigner.execute(AppBundleSigner.java:43)
        at com.bytedance.android.aabresguard.commands.ObfuscateBundleCommand.execute(ObfuscateBundleCommand.java:243)
        at com.bytedance.android.aabresguard.AabResGuardMain.main(AabResGuardMain.java:51)
        at com.bytedance.android.aabresguard.AabResGuardMain.main(AabResGuardMain.java:26)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)

**Comment by Cinkye** [comment]
Same problem.

Below are my env:
Java 11.0.8
gradle 6.1.1
AGP 4.0.1

**Comment by Cinkye** [comment]
> Same problem.
> 
> Below are my env: Java 11.0.8 gradle 6.1.1 AGP 4.0.1

Solved by downloading JDK 11 again and set project's JDK location to it.
Seems that the JDK embedded in AS is incomplete.
