### ISSUE TITLE
Error while generating universal APK

### ISSUE THREAD

**Issue by eakteam** [bytedance/AabResGuard#83]
Trying to run bundle tool command : 

`java -jar "***\bundletools\bundletool.jar" build-apks --bundle="***\app\release\app-release.aab" --output="***\my_app.apks" --ks="***r.jks" --ks-pass=pass:"***" --ks-key-alias="***" --key-pass=pass:"***" --mode=universal --local-testing
`

And it gives me error : 

```
aapt2.exe F 08-12 16:10:46  3636 11112 ProtoDeserialize.cpp:856] unknown compound value: 0
[BT:1.11.0] Error: Command '[C:\Users\***\AppData\Local\Temp\AutoValue_BuildApksCommand12338222067075948085\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\***\AppData\Local\Temp\12362504198736845201\binary2.apk, C:\Users\***\AppData\Local\Temp\12362504198736845201\proto1.apk]' didn't terminate successfully (exit code: -1073740791). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[C:\Users\***\AppData\Local\Temp\AutoValue_BuildApksCommand12338222067075948085\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\***\AppData\Local\Temp\12362504198736845201\binary2.apk, C:\Users\***\AppData\Local\Temp\12362504198736845201\proto1.apk]' didn't terminate successfully (exit code: -1073740791). Check the logs.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
        at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:53)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertAndOptimizeProtoApk(Aapt2ResourceConverter.java:156)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertResourcesToBinary(Aapt2ResourceConverter.java:116)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter.lambda$null$2(Aapt2ResourceConverter.java:96)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by evilhawk00** [comment]
This problem happens with `com.google.android.material:material:1.7.0`, @eakteam check your Google material version. Switching back to `com.google.android.material:material:1.6.1` solve the issue.

**Comment by dj931567261** [comment]
> This problem happens with `com.google.android.material:material:1.7.0`, @eakteam check your Google material version. Switching back to `com.google.android.material:material:1.6.1` solve the issue.

it doesn't work

**Comment by taugin** [comment]
> This problem happens with `com.google.android.material:material:1.7.0`, @eakteam check your Google material version. Switching back to `com.google.android.material:material:1.6.1` solve the issue.

good, Your answer solved my problem

thanks

**Comment by bumptechlab** [comment]
> This problem happens with `com.google.android.material:material:1.7.0`, @eakteam check your Google material version. Switching back to `com.google.android.material:material:1.6.1` solve the issue.

thanks! pal, also solved my problem

**Comment by xeemoo** [comment]
This error is actually due to the aapt2 version being too low. Upgrading the bundletool version in this project can solve the problem.

**Comment by est7** [comment]
@xeemoo 请问那个versions.bundletool 我 fork 一下,只用改一下版本号就行吗,有 breaking changes 吗? 你分叉在哪里,我看 pr 里没,感谢

**Comment by 471448446** [comment]
> [@xeemoo](https://github.com/xeemoo) 请问那个versions.bundletool 我 fork 一下,只用改一下版本号就行吗,有 breaking changes 吗? 你分叉在哪里,我看 pr 里没,感谢

就是修改bundletool 版本，然后重新发布就行。
```
versions.bundletool = "1.17.1"
```
