### ISSUE TITLE
bundleTool转apks失败,google不让提交aab

### ISSUE THREAD

**Issue by deagle-z** [bytedance/AabResGuard#94]
**Describe the bug**
使用androidx.appcompat:appcompat:1.4.0以上版本，打包aab后，使用bundleTool转apks失败,google不让提交aab

 Error: Command '[C:\Users\deagle\AppData\Local\Temp\AutoValue_BuildApksCommand3823752302643610646\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\deagle\AppData\Local\Temp\5238521588075053842\binary2.apk, C:\Users\deagle\AppData\Local\Temp\5238521588075053842\proto1.apk]' didn't terminate successfully (exit code: -1073740791). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[C:\Users\deagle\AppData\Local\Temp\AutoValue_BuildApksCommand3823752302643610646\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\deagle\AppData\Local\Temp\5238521588075053842\binary2.apk, C:\Users\deagle\AppData\Local\Temp\5238521588075053842\proto1.apk]' didn't terminate successfully (exit code: -1073740791). Check the logs.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
        at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:71)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertAndOptimizeProtoApk(Aapt2ResourceConverter.java:158)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertResourcesToBinary(Aapt2ResourceConverter.java:125)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter.lambda$convert$3(Aapt2ResourceConverter.java:105)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by deagle-z** [comment]
修改下描述
androidx.appcompat:appcompat:1.4.1 以上版本导致，打包aab后，使用bundleTool转apks失败
com.google.android.material:material:1.5.0 以上版本，google不让提交aab
原始aab都是可以的

**Comment by Jiang00** [comment]
请问下不降级的话怎么结局，我androidx.appcompat:appcompat:1.6.1打出来的aab包使用bundleTool转apks失败
